####################
- name: Playbook
  hosts: testz
  become: yes
  become_user: root
  vars:
       mysql_root_password: password
  tasks:
       - name: install mysql server
         apt:
          name: mysql-server
          state: present
       - name: install client mysql
         apt:
          name: mysql-client
          state: present
       - name: start up the mysql service
         shell: "service mysql start"
       - name: ensure mysql is enabled to run on startu
         service: name=mysql state=started enabled=true
       - name: update mysql root password for all root accounts  
         mysql_user:  
           name: root  
           host: "{{ item }}"  
           password: "{{ mysql_root_password }}"  
           login_user: root  
           login_password: "{{ mysql_root_password }}"  
           check_implicit_admin: yes  
           priv: "*.*:ALL,GRANT"  
             # with_items:  
             #     - "{{ ansible_hostname }}"
